sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t aghayevali/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aghayevali/docker-react npm run test